controller:
  replicaCount: 1
  ingressClass: 'nginx'
  config:
    ssl-redirect: "false"
    hsts: "true"
    use-forwarded-headers: "true"
    custom-http-errors: 413,502,503,504
  service:
    targetPorts:
      http: http
      https: http
    externalTrafficPolicy: 'Local'
    omitClusterIP: true
defaultBackend:
  enabled: true
  image:
    repository: defaultbackend
    tag: v1.0.9
  port: 3000
